### ISSUE TITLE
Deprecated constructors

### ISSUE THREAD

**Issue by CharlesButcher** [Piwigo/piwigo-akismet#1]
PHP warning: 

> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; AkismetHttpClient has a deprecated constructor in...
.../rv_akismet/akismet.class.php on line 116
.../rv_akismet/akismet.class.php on line 189

Could some kind person please fix this? It's beyond my skill.

**Comment by Hood-fr** [comment]
Also have the issue. I propose this correction https://github.com/modus75/piwigo-akismet/pull/2/commits/dd2568c7b7e5bdff404721549906a37f8dceecdb

**Comment by CharlesButcher** [comment]
Thanks for this! Unfortunately I get an error `unexpected '}'` on line 184. When I remove that, I get:

`Fatal error: Cannot use "self" when no class scope is active` on line 135 (previously line 134, `function AkismetHttpClient`). Presumably `function Akismet` will give the same error.

This is with PHP 7.x – does that make any difference?

**Comment by Hood-fr** [comment]
Did you copy the entire file ?
} of line 184 is required as it closes the class AkismetHttpClient class opened on line 116. 
So put it back and make sure your code does not contain an extra } somewhere else.

**Comment by CharlesButcher** [comment]
Yes, sorry! I tried to do it line by line, and must have made a mistake. Seems to be working fine now :-)

**Comment by plegall** [comment]
Will be fixed by @Hood-fr pull-request in version 12.a of the plugin
